export const ALLEGIANCES = {
  "As": "Aslan Hierate",
  "At": "Anubian Trade Coalition",
  "Bs": "Belgardian Sojurnate",
  "Cs": "Client State",
  "Dr": "Droyne World",
  "Hv": "Hive Federation",
  "Im": "Imperium",
  "Kk": "K'kree Two Thousand Worlds empire",
  "Na": "",
  "So": "Solomani Confederation",
  "Zh": "Consulate",
  "Cw": "Chirper World",
  "Dd": "Domain of Deneb",
  "Fd": "Federation of Daibei",
  "Fi": "Federation of Ilelish",
  "La": "League of Antares",
  "Li": "Lucan's Imperium",
  "Ma": "Margaret's Stronghold",
  "Rv": "Restored Vilani Empire",
  "St": "Strephon's Imperium",
  "Wi": "Wilds",
  "Zc": "Zodia Colonies",
  "Ca": "Carrillian Assembly",
  "Pc": "Principality of Caledon",
  "Ct": "Carter Technocracy",
  "Cl": "Council of Leh Perash",
  "Cu": "Cytralin Unity",
  "Dc": "Confederation of Duncinae",
  "Fh": "Federation of Heron",
  "Fl": "Florian League",
  "Gr": "Gamma Republic",
  "Gm": "Grand Duchy of Marlheim",
  "Gd": "Grand Duchy of Stoner",
  "Go": "Gerontocracy of Ormine",
  "Ge": "Glorious Empire",
  "Gf": "Glimmerdrift Federation",
  "Gc": "Gniivi Collective",
  "Id": "Islaiat Dominate",
  "Ju": "Imperium",
  "Kl": "Khuur League",
  "Lr": "Loyal Nineworlds Republic",
  "Lc": "Lanyard Colonies",
  "Me": "Maskai Empire",
  "Ow": "Outcasts of the Whispering Sky",
  "Ra": "Ral Ranta",
  "Sf": "Senlis Foederate",
  "Sc": "Strend Cluster",
  "Sw": "Sword Worlds Confederation",
  "Ta": "Tealou Arlaoh (Aslan independent clan, non-outcast)",
  "Uh": "Union of Harmony",
  "V4": "40th Squadron (Ekhelle Ksafi)",
  "Ac": "Anti-Rukh Coalition (Gnoerrgh Rukh Lloell)",
  "Ua": "United Followers of Augurgh",
  "Ba": "Bakne Alliance",
  "Ck": "Commonality of Kedzudh (Kedzudh Aeng)",
  "Df": "Dzarrgh Federate",
  "Pg": "Pact of Gaerr (Gaerr Thue)",
  "Rs": "Rranglloez Stronghold",
  "Wr": "Worlds of Leader Rukh (Rukh Aegz)",
  "Sd": "Saeknouth Dependency (Saeknouth Igz)",
  "Se": "Society of Equals (Dzen Aeng Kho)",
  "Te": "Thirz Empire (Thirz Uerra)",
  "Ur": "Urukhu",
  "Ev": "Empire of Varroerth",
  "Pw": "People of Wanz",
  "Wp": "Windhorn Pact of Two"
};
